version: 2.1

executors:
  default_executor:
    working_directory: ~/laravel
    docker:
      - image: circleci/php:7.4-node-browsers
        environment:
          LOCALE: ja
          LANG: ja_JP.UTF-8
          TZ: /usr/share/zoneinfo/Asia/Tokyo
          APP_ENV: testing
          DB_DATABASE: laravel_test

      - image: circleci/mysql:5.7
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin --innodb-large-prefix=true --innodb-file-format=Barracuda
        environment:
          TZ: /usr/share/zoneinfo/Asia/Tokyo
          MYSQL_USER: root
          MYSQL_ALLOW_EMPTY_PASSWORD: true

jobs:
  build:
    executor: default_executor
    steps:
      - checkout

      - run:
          name: Install PHP dependencies
          command: |
            sudo apt update
            sudo apt install default-mysql-client zlib1g-dev libpng-dev fonts-ipafont-gothic
            sudo docker-php-ext-install zip gd pdo_mysql
            sudo composer self-update

      - run:
          name: Set env
          command: |
            cp .env.example .env

      # Download and cache dependencies
      # composer cache
      - restore_cache:
          keys:
            - composer-v1-{{ checksum "composer.lock" }}
            - composer-v1-
      - run: composer install -n --ignore-platform-reqs
      - save_cache:
          key: composer-v1-{{ checksum "composer.lock" }}
          paths:
            - vendor

      # node cache
      - restore_cache:
          keys:
            - node-v1-{{ checksum "yarn.lock" }}
            - node-v1-
      - run: yarn
      - save_cache:
          key: node-v1-{{ checksum "yarn.lock" }}
          paths:
            - node_modules

      - run:
          name: Run phpstan
          command: |
            vendor/bin/phpstan analyse

      - run:
          name: Wait for DB
          command: |
            dockerize -wait tcp://127.0.0.1:3306 -timeout 120s

      - run:
          name: Create database
          command: |
            mysql -h 127.0.0.1 -uroot -e "CREATE DATABASE laravel_test"

      - run:
          name: Generate APP_KEY
          command: |
            php artisan key:generate

      - run:
          name: Run test
          command: |
            phpdbg -qrr vendor/bin/phpunit --log-junit ~/phpunit/junit.xml --coverage-html ~/phpunit/coverage-report

      - store_test_results:
          path: ~/phpunit

      - store_artifacts:
          path: ~/phpunit

      - run:
          name: Install Chrome Driver
          command: |
            php artisan dusk:chrome-driver

      - run:
          name: Start Chrome Driver
          command: |
            vendor/laravel/dusk/bin/chromedriver-linux
          background: true

      - run:
          name: Migrate
          command: |
            php artisan migrate

      - run:
          name: Run Laravel Server
          command: |
            php artisan serve --port=9000
          background: true

      - run:
          name: Run Laravel Dusk Test
          command: |
            php artisan dusk

      - store_artifacts:
          path: ~/tests/Browser/screenshots
